### PR TITLE
Upgraded ci and deps

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
- add node 5 to travis
- setup coverage
- CI badges
- Update deps and tests

:smiley:

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Support was drop from hapi. cf: https://github.com/hapijs/hapi/issues/2764

Hence test failing on 0.10 when upgrading deps
cf: https://travis-ci.org/AdrieanKhisbe/hapi-authorization/jobs/97230488
test failing because of `const`

**Comment by toymachiner62** [comment]
Ah got it. I'll update the Readme to reflect that then. Thanks a lot. I'll get this merged soon.

**Comment by AdrieanKhisbe** [comment]
was a pleasure :), or should I say *"was hapi to do be of any help"*

I recommend to release a major then. (since 1 already been reached :))

**Comment by toymachiner62** [comment]
3.0.0 published to NPM.

**Comment by AdrieanKhisbe** [comment]
cool! :)

**Comment by AdrieanKhisbe** [comment]
(you just need to activate coveralls repo (log with github), and we'll have the coverage reported :) )

**Pull request merged**
